{% set name = "ecco" %}
{% set version = "0.1.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/ecco-{{ version }}.tar.gz
  sha256: b0b280b3214f19fca28a74aec0e0c332693ccd3f621b79102dac69f902e1ffb2

build:
  number: 1
  noarch: python
  entry_points:
    - ecco = ecco.cli:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    - captum ~=0.4
    - pyyaml ~=5.4
    - scikit-learn ~=0.23
    - seaborn ~=0.11
    - transformers ~=4.2
    # NOTE:
    # The install_requires does not include "ipython"
    # But, the package build fails without "ipython" 
    # on conda-forge.
    - ipython

test:
  imports:
    - ecco
  commands:
    - pip check
    - ecco --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/jalammar/ecco
  summary: Visualization tools for NLP machine learning models.
  license: BSD-3-Clause
  license_file: LICENSE
  description: |
    Ecco is a python library for explaining Natural Language 
    Processing models using interactive visualizations.

    It provides multiple interfaces to aid the explanation 
    and intuition of [Transformer][_transformer]-based language models. 
    Read: [Interfaces for Explaining Transformer Language Models][_interfaces].

    Ecco runs inside Jupyter notebooks. It is built on top 
    of [pytorch][_pytorch] and [transformers][_hf-transformers].

    The library is currently an alpha release of a research 
    project. Not production ready. You're welcome to contribute 
    to make it better!

    [_transformer]: https://jalammar.github.io/illustrated-transformer/
    [_interfaces]: https://jalammar.github.io/explaining-transformers/
    [_pytorch]: https://pytorch.org/
    [_hf-transformers]: https://github.com/huggingface/transformers

    List of Web Resources:

      - [Ecco - *Look Inside Language Models*](https://www.eccox.io/)
      - [Finding the Words to Say: Hidden State Visualizations for Language Models](https://jalammar.github.io/hidden-states/)

  doc_url: https://ecco.readthedocs.io/
  dev_url: https://github.com/jalammar/ecco

extra:
  recipe-maintainers:
    - sugatoray
